version: 0.1
resourceType: variables
variables:
  simpleKey: variable
  region:                     'us-east-2'     ## You can set region for deployment here
  default_region:             'us-east-2'     ## If key region is not present it is default region setter
  profile:                    'default'       ## It chooses profile from your ~/.aws config. If not present, profile is `default`
  network_name:               'sidechain-example'
  number_of_nodes:            '5'
  quorum_docker_image_tag:    '2.2.5'
  #  aws_access_key_id:       'dummyValue'    ## It overrides access key id env variable. If omitted system env is used
  #  aws_secret_access_key:   'dummyValue'    ## It overrides secret access key env variable. If omitted system env is used
  genesis_gas_limit:          "28"   ## Used to set genesis gas limit
  genesis_timestamp:          "30"         ## Used to set genesis timestamp
  genesis_difficulty:         "12"          ## Used to set genesis difficulty
  genesis_nonce:              "0"          ## Used to set genesis nonce
#  consensus_mechanism:       "instanbul"    ## Used to set consensus mechanism
#  chaos_testing_run_command: ["netem", "--duration", "5m", "--interface", "eth0", "delay", "--time", "3000", "--jitter", "30", "--correlation", "20", "re2:^ecs-quorum*"]
